# Generated by Django 5.0.2 on 2024-11-11 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='plantation_images/')),
                ('plantation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.plantation')),
            ],
        ),
    ]
