# Generated by Django 5.0.2 on 2024-11-11 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_plantationimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
