# Generated by Django 5.0.2 on 2024-11-12 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_customuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantation',
            name='total_area',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='PlantationFruitArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.FloatField()),
                ('fruit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.fruits')),
                ('plantation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fruit_area', to='api.plantation')),
            ],
        ),
    ]
