# Generated by Django 5.0.2 on 2024-11-12 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_plantation_total_area_plantationfruitarea'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantation',
            name='fruit_type',
        ),
    ]
