# Generated by Django 5.0.2 on 2024-11-18 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_plantation_is_deleting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantation',
            name='prev_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
