# Generated by Django 5.0.2 on 2024-11-19 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_plantation_owner_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantation',
            name='owner_number',
        ),
    ]
