# Generated by Django 5.0.2 on 2024-11-25 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_plantation_owner_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='FruitVariety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('fruit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='varieties', to='api.fruits')),
            ],
        ),
        migrations.AddField(
            model_name='plantationfruitarea',
            name='variety',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fruit_areas', to='api.fruitvariety'),
        ),
    ]
