# Generated by Django 5.0.2 on 2024-11-28 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_fruitvariety_plantationfruitarea_variety'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='districts',
        ),
        migrations.AddField(
            model_name='customuser',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='api.district'),
        ),
    ]
